application: stunning-adgen
version: 1
runtime: php55
api_version: 1
default_expiration: 0s

handlers:
- url: /adgen
  static_files: adgen/index.html
  upload: adgen/index.html

# Serve php scripts.
- url: /adgen/(.+\.php)$
  script: /adgen/\1

# Serve static files
- url: /adgen/(.*\.(gif|png|jpg|css|js|html|json|ttf|woff))$
  static_files: adgen/\1
  upload: adgen/.*\.(gif|png|jpg|css|js|html|json|ttf|woff)$