application: start-stunning
version: 1
runtime: php55
api_version: 1

handlers:
  - url: /gallery
    static_files: gallery/index.html
    upload: gallery/index.html

  - url: /gallery/(.+)
    static_files: gallery/\1
    upload: gallery/(.*)

  - url: /adgen
    static_files: adgen/index.html
    upload: adgen/index.html

  - url: /adgen/(.+)
    static_files: adgen/\1
    upload: adgen/(.*)
